### ISSUE TITLE
AIS_VD Plugin future

### ISSUE THREAD

**Issue by Hakansv** [RooieDirk/AIS_VD_pi#1]
@RooieDirk 
Dirk..
Based on a request from a small tanker ship I supplied with OCPN I started to look for possibilities to add AIS static data in OCPN.
Now I found this plugin and realized it's no need to "invent the wheel". Excellent! And to make it a plugin is also a good idea since a lot AIS-B users will have "limited interest".
Some questions without to stress or demanding actions.
- Do you have any plans for Pluginmanager adaption?
- Can I contribute in some way although you know my limited coding capabilities?

Håkan

**Comment by RooieDirk** [comment]
Hai Håkan,
For me it is an abonded project, but  if you want to contribute by adding pi-manager support it would be appreciated. And not only by me. 
Feel free to fork the code and push it to the plugin page yourself.
succes.
WKR
Dirk

**Comment by Hakansv** [comment]
Hej Dirk..
Thanks, I'll make a try to understand the, for me not straight forward, pi-manager process. This "little" pi may be a suitable object to learn. And any hints are of course appreciated.
I'll keep you informed.
Håkan

**Comment by RooieDirk** [comment]
The easiest is (I think) to take copy of Jon's test plugin https://github.com/jongough/testplugin_pi, and replace the 'payload' with the ais_pi code.
And ofcourse read the manual/wiki pages ;-)

**Comment by Hakansv** [comment]
re: "And of course read the manual/wiki pages"
-- more explicit.. what wiki do you refer to??
Thanks.
Håkan

**Comment by RooieDirk** [comment]
Here:
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:pi_installer_summary
and from here in the manual you will find links to a separated wiki plugin pages.

**Comment by Hakansv** [comment]
Very good! I'll study.

**Comment by Hakansv** [comment]
A Win tarball created - so far so good. Next exciting step is to upload to OpenCPN/Plugins...... (Phuu..)
A Q:
What's your intention with the AIS type selection, see pic 3? 
I can imagine a preparation for password protected static "Ship type"? But I've instead omitted to send that info. It would have been set using the AIS itself and it's not "voyage data

![bild](https://user-images.githubusercontent.com/7202854/131231346-33cd83e5-cff6-4cb4-9d7e-064167e52cbd.png)

![bild](https://user-images.githubusercontent.com/7202854/131231354-c1d044d7-7bb5-4661-beaf-57cf3331facd.png)

![bild](https://user-images.githubusercontent.com/7202854/131231410-507fd2df-d58c-4a42-91cb-1f1c048fc835.png)

**Comment by RooieDirk** [comment]
So far so good. I do know it is a steep learning curve, so you must have done a lot of work.
Here in the Netherlands there are a lot of 'dual' ais tranceivers. These can switch between sea and inland mode. For the switching you need a proprietary nmea sentence (with password). That's why I had a type selection. But it also makes things rather complicated.
F.y.i I only did test the code with the TrueHeading AIS.

**Comment by Hakansv** [comment]
As I understand it there are some transceivers with password for static data like ship type and also to switch between sea and inland modes. 
My intention is to send voyage data only and thus no need for the password string. This is so far "hearsay" and not yet verified by me. My idea is OpenCPN can update daily voyage data but when it comes to static, proprietary?, data the "normal" AIS interface has to be used.
When I've a working tarball creation (still a minor issue) it's easier to perform tests on others system.
My next steps and considerations when time allows:
- Test on class A transceivers at the workshop I occasionally visit.
- Test on "live" system onboard a boat by sending the tarball for import by the crew.
- Add an inland option, i.e. selection between sea/inland and thus adapt the appropriate "Talker". I'm not yet sure how to test that.
- When verified push to OpenCPN/Plugins.

**Comment by RooieDirk** [comment]
An advice, forget about the inland for now. Just comment out all the code parts for that. For inland you should also be able to set the kind of cargo, and for ea push barges it should be possible to change the vessel dimensions.
The whole inland issue was the main reason for not to continue the project.

**Comment by Hakansv** [comment]
OK, thanks.
Now some issues with pluginmanager are solved. 
Time to hunt for a AIS to test. :)

**Comment by rvpstech** [comment]
Hello. I am currently sailing onboard the R/V Point Sur and do not have the bandwidth available to downlead the tools required to compile. Do you happen to have a precompiled binary for Windows and/or did you ever get this ported to work with the plugin manager?

**Comment by Hakansv** [comment]
@rvpstech
Well, I have not yet been able to test this function on a AIS type A transceiver. The one I had on the desk some weeks ago wasn't available for me to play with since the installation on board the desired ship was to coveted to get it and leave. So the function is not at all confirmed.
But if you want to make a test it's really appreciated. 
Attached is a Windows tarball for "Import" by the plugin manager. After import make an install and don't forget to activate.
See pictures on above post for how to use it.
Thanks
Håkan

[AIS_VD-1.1.9-Beta_msvc-10.0.19042-win32.tar.gz](https://github.com/RooieDirk/AIS_VD_pi/files/7391824/AIS_VD-1.1.9-Beta_msvc-10.0.19042-win32.tar.gz)

**Comment by rvpstech** [comment]
Thanks! If I can get this working I'll make make sure to keep you posted.

**Comment by Hakansv** [comment]
Your welcome and please tell me also what's is not working.

**Comment by Hakansv** [comment]
@rvpstech 
I've been able able to test a little on a although partly broken transponder but I can still see message No 1.
I saw some obstacles corrected in the attached tarball.
[AIS_VD-1.1.12-Beta_msvc-10.0.19042-win32.tar.gz](https://github.com/RooieDirk/AIS_VD_pi/files/7425963/AIS_VD-1.1.12-Beta_msvc-10.0.19042-win32.tar.gz)

**Comment by Hakansv** [comment]
@rvpstech 
Ooops.. A small bug in version 1.1.12. Another one here:
[AIS_VD-1.1.13-Beta_msvc-10.0.19042-win32.tar.gz](https://github.com/RooieDirk/AIS_VD_pi/files/7426817/AIS_VD-1.1.13-Beta_msvc-10.0.19042-win32.tar.gz)

**Comment by Hakansv** [comment]
Dirk..
I've got me an old SAAB R3 to test on. On Win it's working fine.: https://www.dropbox.com/s/iaa4jm6rwtw8bwb/ais-vd-1.1.16-beta%2B2111131426.3d149c0_msvc-10.0.19042-win32.tar.gz?dl=1
As can be seen here: https://github.com/OpenCPN/plugins/issues/490 I can't get it run on Debian Buster though. My Linux experiences are very limited. If you have the time and joy to have a look you may find out the failure?
Here's the code as it's now: https://github.com/Hakansv/ais-vd_pi/tree/test
Branch "test" is the latest. (I renamed it to ais-vd_pi to be sure it was not the underscore creating the obstacle.)
Thanks
Håkan

**Comment by Hakansv** [comment]
Linux run time problem solved.
This declaration was not needed and Linux rejected, Win not.
class aisvd_pi : public opencpn_plugin_116 
{
  -DECLARE_EVENT_TABLE()
  public:
    aisvd_pi(void *ppimgr);
	  ~aisvd_pi();

**Comment by Hakansv** [comment]
This plugin may soon be in OCPN plugin manager. Pls continue any issues here: https://github.com/Hakansv/ais-vd_pi/issues
